springdoc:
  swagger-ui:
    path: ${API_DOCS_PATH}
    oauth2-redirect-url: ${REDIRECT_URL_DEV}
    oauth:
      client-id: ${GOOGLE_CLIENT_ID_DEV}
      client-secret: ${GOOGLE_SECRET_KEY_DEV}
      scopes:
        - profile
        - email
        - https://www.googleapis.com/auth/gmail.readonly
      useBasicAuthenticationWithAccessCodeGrant: true
      usePkceWithAuthorizationCodeGrant: true

spring:
  config:
    activate:
      on-profile: dev
    import: application.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PW_DEV}

  data:
    redis:
      port: 6379
      host: ${REDIS_HOST_DEV}
      repositories:
        enabled: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID_DEV}
            client-secret: ${GOOGLE_SECRET_KEY_DEV}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/gmail.readonly # Gmail 읽기 권한
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo